### ISSUE TITLE
OPO - kali nethunter issue

### ISSUE THREAD

**Issue by gitty8** [hkm/whoishere.py#5]
I changed wlan0mon to wlan1mon, after running I getting this:

```
PHY     Interface       Driver          Chipset

phy0    p2p0            ??????          Not pci, usb, or sdio
phy0    wlan0           ??????          Not pci, usb, or sdio
phy5    wlan1           ??????          Atheros Communications, Inc. AR9271 802.11n

                (mac80211 monitor mode already enabled for [phy5]wlan1 on [phy5]10)
root@kali:~/whoishere.py-master# python whoishere.py

        /         /      /
       (___  ___    ___ (___  ___  ___  ___
  |   )|   )|   )| |___ |   )|___)|   )|___)
  |/\/ |  / |__/ |  __/ |  / |__  |    |__

           WIFI Client Detection 0.2

  Author: Pedro Joaquin @_hkm (pjoaquin@websec.mx)
  To kill this script hit CRTL-C


[+] Current List:
    # :        MAC        -    NAME
    0 : dc:53:60:67:7d:ca - James Clerk Maxwell
    1 : 6C:AD:F8:27:85:CA - Christian Hulsmeyer
    2 : e0:b5:2d:0a:d4:a4 - Heinrich Hertz

[+] Configuration:
    Current Time            [2017-04-21 11:59]
    Configuration File      [whoishere.conf]
    Log File                [whoishere.log]
    Monitor Interface       [wlan1mon]
    Pushover Notifications  [Disabled]


[+] Listening for probe requests...

Traceback (most recent call last):
  File "whoishere.py", line 155, in <module>
    sniff(iface=interface, prn = PacketHandler, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 593, in sniff
    **karg)]
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 488, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device
root@kali:~/whoishere.py-master#
```

**Comment by l-pa** [comment]
Change device in .conf file?

**Comment by gitty8** [comment]
do you mean Monitor Interface?

**Comment by loviuz** [comment]
it seems that wlan1mon doesn't exists in your list of devices. try wlan1 if monitor mode has been enabled on it. ther error is "no such device", it means that the device specified (wlan1mon) does't exists

**Comment by hussnain27** [comment]
Is the nethunter kernel compatible with all devices (I have huawei media pad)

**Comment by gitty8** [comment]
@loviuz
Wifite working without issues. Wlan1mon device is online.
