### ISSUE TITLE
TypeError: ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by greaterthanstar** [hkm/whoishere.py#9]
Traceback (most recent call last):
  File "whoishere.py", line 155, in <module>
    sniff(iface=interface, prn = PacketHandler, store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 925, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sessions.py", line 47, in on_packet_received
    result = self.prn(pkt)
  File "whoishere.py", line 133, in PacketHandler
    PrintInfo(pkt)
  File "whoishere.py", line 107, in PrintInfo
    db = -(256-ord(pkt.notdecoded[-4:-3]))
TypeError: ord() expected a character, but string of length 0 found

**Comment by greaterthanstar** [comment]
This is right upon starting it and after it displays the conf info

**Comment by loviuz** [comment]
You can change:
> db = -(256-ord(pkt.notdecoded[-4:-3]))

with:
> db = pkt.dBm_AntSignal

It should work.
